---
- name: Deploy VM su VMware
  hosts: localhost
  gather_facts: no
  vars:
    validate_certs: no
    esxi_host: "yesxba04.yoctoitba.local"
    vm_datacenter: "YoctoIT Basiglio DC"
    vm_cluster: "YoctoIT VMWare Farm Basiglio"
    vm_network: "0690_yService"
    vm_datastore: "yDS01_V7K"
    vm_template: "W2019-Tmpl-202411"
    vm_cpu: 2
    vm_memory: 4096
    vm_disk: 40
  tasks:
    - name: Clonare una VM dal template
      community.vmware.vmware_guest:
        # vCenter host e credenziali sono gestiti dalla credenziale associata al Job Template
        hostname: "10.243.60.20" # Non è necessario definirla nel playbook
        username: "{{ vcenter_username }}"  # Gestito dal Vault di AWX
        password: "{{ vcenter_password }}"  # Gestito dal Vault di AWX
        validate_certs: no
        datacenter: "{{ vm_datacenter }}"
        cluster: "{{ vm_cluster }}"
        folder: "/{{ vm_datacenter }}/vm/Ansible"
        name: "{{ vm_name }}"  # Prompted variable
        template: "{{ vm_template }}"
        state: poweredon
        hardware:
          memory_mb: "{{ vm_memory }}"
          num_cpus: "{{ vm_cpu }}"
        networks:
          - name: "{{ vm_network }}"
        disk:
          - size_gb: "{{ vm_disk }}"
            type: thin
            datastore: "{{ vm_datastore }}"
      register: vm_result  # Salviamo il risultato per estrarre l'IP

    - name: "Salvare l'IP della VM"
      set_fact:
        vm_ip: "{{ vm_result.instance.ipAddress }}"  # Estrae l'IP

    - name: Debug dell'IP della VM
      debug:
        msg: "L'IP della VM è: {{ vm_ip }}"
