---
- name: Deploy VM su VMware
  hosts: localhost
  gather_facts: no
  vars:
    validate_certs: no
    esxi_host: "yesxba04.yoctoitba.local"
    vm_datacenter: "YoctoIT Basiglio DC"
    vm_cluster: "YoctoIT VMWare Farm Basiglio"
    vm_network: "0690_yService"
    vm_datastore: "yDS01_V7K"
    vm_template: "W2019-Tmpl-202411"
    vm_cpu: 2
    vm_memory: 4096
    vm_disk: 40
  tasks:
    - name: Clonare una VM dal template
      community.vmware.vmware_guest:
        hostname: "{{ lookup('ansible.builtin.env', 'VMWARE_HOST') }}"  # vCenter host
        username: "{{ lookup('ansible.builtin.env', 'VMWARE_USER') }}"  # vCenter username
        password: "{{ lookup('ansible.builtin.env', 'VMWARE_PASSWORD') }}"  # vCenter password
        validate_certs: no
        datacenter: "{{ vm_datacenter }}"
        cluster: "{{ vm_cluster }}"
        folder: "/{{ vm_datacenter }}/vm/Ansible"
        name: "{{ vm_name }}"  # Prompted variable
        template: "{{ vm_template }}"
        state: poweredon
        hardware:
          memory_mb: "{{ vm_memory }}"
          num_cpus: "{{ vm_cpu }}"
        networks:
          - name: "{{ vm_network }}"
        disk:
          - size_gb: "{{ vm_disk }}"
            type: thin
            datastore: "{{ vm_datastore }}"
      register: vm_result  # Salviamo il risultato per estrarre l'IP

    - name: Debug dell'output della VM
      debug:
        msg: "{{ vm_result }}"

    - name: Attendere che la VM risponda al ping
      wait_for:
        host: "{{ vm_name }}"
        port: 3389  # Per esempio, RDP (puoi usare qualsiasi porta aperta sulla VM)
        state: started
        timeout: 300  # Tempo massimo per aspettare
        delay: 10     # Intervallo tra i tentativi
      register: vm_ping

    - name: Recupera l'IP della VM dalla risorsa
      set_fact:
        vm_ip: "{{ vm_result.instance.networks[0].ipAddresses[0] }}"  # Cambia questa parte se l'IP è in un'altra struttura
      when: vm_ping.state == 'started'

    - name: Debug dell'IP della VM
      debug:
        msg: "L'IP della VM è: {{ vm_ip }}"
