---
- name: Verifica la connettività della VM
  hosts: localhost
  gather_facts: no
  vars:
    vm_ip: "{{ vm_ip }}"  # Variabile passata dal playbook precedente

  tasks:
    - name: Verifica la connettività della VM (Ping)
      wait_for:
        host: "{{ vm_ip }}"
        state: started
        timeout: 300  # 5 minuti di attesa
        delay: 10     # intervallo tra i tentativi
        port: 0       # port 0 indica l'uso di ping (ICMP)
        ping: yes      # Abilita il controllo ping ICMP
